# Generated by Django 4.0 on 2023-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmatpeligroso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
