# Generated by Django 4.0 on 2023-06-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='username',
        ),
    ]
