# Generated by Django 4.0 on 2023-06-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_usuarios_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
