# Generated by Django 4.0 on 2023-06-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_remove_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='campus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bitacora.campus', verbose_name='campus del departamento'),
        ),
    ]
