# Generated by Django 4.0 on 2023-06-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_alter_departamentos_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmatpeligroso',
            name='ficha_seguridad',
            field=models.FileField(null=True, upload_to='fichas_seguridad/'),
        ),
        migrations.AlterField(
            model_name='catmatpeligroso',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='regalmacen',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bitacora.uproducto', verbose_name='producto del almacen'),
        ),
    ]
