# Generated by Django 4.0 on 2023-06-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0005_alter_catmatpeligroso_ficha_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmatpeligroso',
            name='ficha_seguridad',
            field=models.FileField(blank=True, null=True, upload_to='fichas_seguridad/'),
        ),
        migrations.AlterField(
            model_name='catmatpeligroso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
